version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: aGZyMfh5Jz3uVGYpMbQSdLNZn7MBEOOq+dM0b9QLJcKo82mSldrrXSeGbZNhYGyP
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- ps: ./Start-Gremlin-Server.ps1
test_script:
- ps: ./Coverage.ps1